### ISSUE TITLE
internal server fails when receive data from external server

### ISSUE THREAD

**Issue by gotti** [ueckoken/plarail2021-soft#108]
```
goroutine 50 [running]:
ueckoken/plarail2021-soft-internal/pkg.SendJson({0xc0001320b0, 0x10}, {0xc000334018, 0x16, 0x18}, 0x3b9aca00)
	/mnt/live/projects/koken/latest-plarail/plarail2021-soft/backend/internal/pkg/sendJson.go:13 +0x107
ueckoken/plarail2021-soft-internal/internal.(*Send2node).Send2Esp(0xc0000afaa8)
	/mnt/live/projects/koken/latest-plarail/plarail2021-soft/backend/internal/internal/sendMsg2Esp.go:34 +0x5e
ueckoken/plarail2021-soft-internal/internal.(*ControlServer).Command2Internal(0xc000116d90, {0x89603b, 0xc0003026f0}, 0xc0003080c0)
	/mnt/live/projects/koken/latest-plarail/plarail2021-soft/backend/internal/internal/ServeCommand2Internal.go:24 +0x105
ueckoken/plarail2021-soft-internal/spec._Control_Command2Internal_Handler.func1({0xa78af8, 0xc000302210}, {0x96c660, 0xc0003080c0})
	/mnt/live/projects/koken/latest-plarail/plarail2021-soft/backend/internal/spec/statesync_grpc.pb.go:82 +0x78
github.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).UnaryServerInterceptor.func1({0xa78af8, 0xc000302210}, {0x96c660, 0xc0003080c0}, 0xc000076bb8, 0xc000330228)
	/home/gotti/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-prometheus@v1.2.0/server_metrics.go:107 +0x87
ueckoken/plarail2021-soft-internal/spec._Control_Command2Internal_Handler({0x93f0a0, 0xc000116d90}, {0xa78af8, 0xc000302210}, 0xc00032e0c0, 0xc0001aa120)
	/mnt/live/projects/koken/latest-plarail/plarail2021-soft/backend/internal/spec/statesync_grpc.pb.go:84 +0x138
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00015a000, {0xa83110, 0xc0000e4480}, 0xc000332000, 0xc00011cd50, 0xe210a0, 0x0)
	/home/gotti/go/pkg/mod/google.golang.org/grpc@v1.41.0/server.go:1279 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc00015a000, {0xa83110, 0xc0000e4480}, 0xc000332000, 0x0)
	/home/gotti/go/pkg/mod/google.golang.org/grpc@v1.41.0/server.go:1608 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	/home/gotti/go/pkg/mod/google.golang.org/grpc@v1.41.0/server.go:923 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/home/gotti/go/pkg/mod/google.golang.org/grpc@v1.41.0/server.go:921 +0x294
exit status 2
```

**Comment by gotti** [comment]
おちる
```
gRPC Err: rpc error: code = Unavailable desc = sender err parse "192.168.1.1:8080": first path segment in URL cannot contain colon; not connected to Node
```

**Comment by gotti** [comment]
よさそう
```
gRPC Err: rpc error: code = Unavailable desc = sender err Post "http://192.168.1.1:8080": dial tcp 192.168.1.1:8080: connect: connection refused; not connected to Node
```

**Comment by Azuki-bar** [comment]
> おちる
> 
> ```
> gRPC Err: rpc error: code = Unavailable desc = sender err parse "192.168.1.1:8080": first path segment in URL cannot contain colon; not connected to Node
> ```
```
parse "192.168.1.1:8080": first path segment in URL cannot contain colon; not connected to Node
```
は
https://github.com/ueckoken/plarail2021-soft/blob/acf607bb879a0c9a0eccf7f20e24834e35e80435/backend/internal/internal/ServeCommand2Internal.go#L27

から来るものです。

**Comment by Azuki-bar** [comment]
#110 にて修正されましたのでクローズとします
